/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.CardLayout;

/**
 *
 * @author 91983
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form ReturnBook
     */
    //CardLayout cardLayout;
    public ReturnBook() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textField_1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        textField_2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textField_3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textField_4 = new javax.swing.JTextField();
        textField_5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textField_6 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(441, 200, 1140, 639));
        setMinimumSize(new java.awt.Dimension(1140, 639));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(28, 12, 91));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RETURN BOOK");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(310, 30, 380, 100);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_48px_1.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 50, 54, 55);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_multiply_30px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel3.add(jLabel5);
        jLabel5.setBounds(1100, 10, 34, 44);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_subtract_30px_1.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel3.add(jLabel6);
        jLabel6.setBounds(1050, 10, 30, 44);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_borrow_book_100px_1.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(700, 40, 115, 80);

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(0, 0, 1030, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1140, 150);

        jPanel1.setBackground(new java.awt.Color(201, 150, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel24.setText("BOOK ID* :");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(235, 35, 117, 25);

        textField.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField);
        textField.setBounds(357, 29, 190, 30);

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel17.setText("STUDENT ID* :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(559, 35, 151, 25);

        textField_1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField_1);
        textField_1.setBounds(715, 32, 153, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LMS/icons8_search_24px.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(880, 32, 26, 32);

        jLabel25.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel25.setText("BOOK :");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(76, 158, 72, 25);

        textField_2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField_2);
        textField_2.setBounds(198, 155, 321, 27);

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel14.setText("NAME :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(608, 153, 74, 25);

        textField_3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField_3);
        textField_3.setBounds(727, 150, 341, 27);

        jLabel20.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel20.setText("COURSE :");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(608, 212, 94, 25);

        textField_4.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField_4);
        textField_4.setBounds(727, 209, 341, 27);

        textField_5.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField_5);
        textField_5.setBounds(727, 270, 343, 27);

        jLabel21.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel21.setText("BRANCH :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(608, 273, 101, 25);

        jLabel26.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel26.setText("DATE OF ISSUE :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(76, 212, 164, 25);

        textField_6.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jPanel1.add(textField_6);
        textField_6.setBounds(291, 209, 228, 27);

        jLabel27.setFont(new java.awt.Font("Book Antiqua", 1, 20)); // NOI18N
        jLabel27.setText("DATE OF RETURN :");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(76, 273, 191, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button(4).png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(493, 365, 165, 69);

        jSeparator1.setBackground(new java.awt.Color(28, 12, 91));
        jSeparator1.setForeground(new java.awt.Color(28, 12, 91));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(569, 123, 21, 215);

        jLabel4.setForeground(new java.awt.Color(28, 12, 91));
        jLabel4.setText("_________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 73, 921, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 150, 1140, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        this.setVisible(false);
        new MainPage().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        int i = JOptionPane.showConfirmDialog(null, "Do you want to Exit ?", "EXIT", JOptionPane.YES_NO_OPTION);
        if(i==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MousePressed
    
    public void delete() {
        try {
            Conn con = new Conn();
            String sql = "delete from issueBook where book_id=?";
            PreparedStatement st = con.c.prepareStatement(sql);
            st.setString(1, textField.getText());
            int i = st.executeUpdate();
            if (i > 0)
                JOptionPane.showConfirmDialog(null, "Book Returned");
            else
                JOptionPane.showMessageDialog(null, "error in Deleting");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
	}
    }
    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        Conn con = new Conn();
        try{
          
                String sql = "select * from issueBook where student_id = ? and book_id =?";
		PreparedStatement st = con.c.prepareStatement(sql);
		st.setString(1, textField_1.getText());
		st.setString(2, textField.getText());
		ResultSet rs = st.executeQuery();
		
                while (rs.next()) {
                    textField_2.setText(rs.getString("bname"));
                    textField_3.setText(rs.getString("sname"));
                    textField_4.setText(rs.getString("course"));
                    textField_5.setText(rs.getString("branch"));
                    textField_6.setText(rs.getString("dateOfIssue"));
		}
		st.close();
		rs.close();
		
            }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        //Image icon = Toolkit.getDefaultToolkit().getImage("icons8_search_24px_1");  
        //this.setIconImage(icon);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        //Image icon = Toolkit.getDefaultToolkit().getImage("icons8_search_24px - Copy");  
        //this.setIconImage(icon);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        Conn con = new Conn();
        try{
        String date = ((JTextField)dateChooser.getDateEditor().getUiComponent()).getText();
            String sql = "insert into returnBook(book_id, student_id, bname, sname,course, branch, dateOfIssue, dateOfReturn) values(?, ?, ?, ?, ?, ?, ?, ?)";
		PreparedStatement st = con.c.prepareStatement(sql);
		st.setString(1, textField.getText());
		st.setString(2, textField_1.getText());
		st.setString(3, textField_2.getText());
		st.setString(4, textField_3.getText());
		st.setString(5, textField_4.getText());
		st.setString(6, textField_5.getText());
		st.setString(7, textField_6.getText());

		st.setString(8, date);
		int i = st.executeUpdate();
                // String date = ((JTextField)dateChooser.getDateEditor().getUiComponent()).getText();
		if (i > 0 && !(date.equals("") || (textField_1.getText().equals("")) || (textField.getText().equals("")))) {
                    JOptionPane.showMessageDialog(null, "Examine the received book !!!");
                    delete();
                    textField.setText("");
                    textField_1.setText("");
                    textField_2.setText("");
                    textField_3.setText("");
                    textField_4.setText("");
                    textField_5.setText("");
                    textField_6.setText("");
                    
		} else
                    JOptionPane.showMessageDialog(null, "Please fill all fields !!!");
		
            }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel1MousePressed
    private int xMouse,yMouse; 
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textField;
    private javax.swing.JTextField textField_1;
    private javax.swing.JTextField textField_2;
    private javax.swing.JTextField textField_3;
    private javax.swing.JTextField textField_4;
    private javax.swing.JTextField textField_5;
    private javax.swing.JTextField textField_6;
    // End of variables declaration//GEN-END:variables
}
